-define(CER, #diameter_header{version = 1, application_id = 0, cmd_code = 257, is_request = true}).
-define(CEA, #diameter_header{version = 1, application_id = 0, cmd_code = 257, is_request = false}).
-define(DWR, #diameter_header{version = 1, application_id = 0, cmd_code = 280, is_request = true}).
-define(DWA, #diameter_header{version = 1, application_id = 0, cmd_code = 280, is_request = false}).
